name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip wheel
      - run: pip install bandit codespell flake8
      - run: bandit --recursive --skip B101,B310,B404,B602,B603 .
      - run: codespell --ignore-words-list="noe,ser,villin"
      - run: flake8 --ignore=E12,E22,E231,E261,E265,E30,E70,E711,E722,F401,F841,W29,W391,W504
                    --max-complexity=25 --max-line-length=2624
                    --show-source --statistics .
